### ISSUE TITLE
Add reply to latest message

### ISSUE THREAD

**Issue by gustebeast** [rajeshksv/AlfredExtensions#1]
One of my favorite alfred extensions was one that allowed you reply to your last received text using '.. message'

It made texting from your computer while using other apps much easier. The applescript behind the original extension broke so I attempted to hack up a solution using chat.db

See http://www.alfredforum.com/topic/9226-reply-to-imessage/

Unfortunately that method is very unreliable. Could you perhaps find a better way to implement this feature? It would make your messaging workflow the best one out there.

**Comment by rajeshksv** [comment]
Added the feature. Can you verify
