### ISSUE TITLE
Not seeing my contacts

### ISSUE THREAD

**Issue by gustebeast** [rajeshksv/AlfredExtensions#2]
I'm seeing a different list of contacts including someone named Bongu

**Comment by rajeshksv** [comment]
Ohh.. That's strange .. Are you seeing some additional contacts or completely different contacts ?

As a quick fix, can you do one thing. Go to the workflow directory and remove NamesEmailsPhones file and try again. Let me know if it works .

**Comment by rajeshksv** [comment]
Fixed now. Please verify
